#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportMap")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertgameInfo(gameInfo instance);
  partial void UpdategameInfo(gameInfo instance);
  partial void DeletegameInfo(gameInfo instance);
  partial void InsertgameNews(gameNews instance);
  partial void UpdategameNews(gameNews instance);
  partial void DeletegameNews(gameNews instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SportMapConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<gameInfo> gameInfo
	{
		get
		{
			return this.GetTable<gameInfo>();
		}
	}
	
	public System.Data.Linq.Table<gameNews> gameNews
	{
		get
		{
			return this.GetTable<gameNews>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gameInfo")]
public partial class gameInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gameId;
	
	private int _gameType;
	
	private int _LocationId;
	
	private string _gameNameA;
	
	private string _gameNameB;
	
	private System.DateTime _gameTime;
	
	private decimal _gamestatus;
	
	private int _gameLength;
	
	private decimal _gameResult;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngameIdChanging(int value);
    partial void OngameIdChanged();
    partial void OngameTypeChanging(int value);
    partial void OngameTypeChanged();
    partial void OnLocationIdChanging(int value);
    partial void OnLocationIdChanged();
    partial void OngameNameAChanging(string value);
    partial void OngameNameAChanged();
    partial void OngameNameBChanging(string value);
    partial void OngameNameBChanged();
    partial void OngameTimeChanging(System.DateTime value);
    partial void OngameTimeChanged();
    partial void OngamestatusChanging(decimal value);
    partial void OngamestatusChanged();
    partial void OngameLengthChanging(int value);
    partial void OngameLengthChanged();
    partial void OngameResultChanging(decimal value);
    partial void OngameResultChanged();
    #endregion
	
	public gameInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int gameId
	{
		get
		{
			return this._gameId;
		}
		set
		{
			if ((this._gameId != value))
			{
				this.OngameIdChanging(value);
				this.SendPropertyChanging();
				this._gameId = value;
				this.SendPropertyChanged("gameId");
				this.OngameIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameType", DbType="Int NOT NULL")]
	public int gameType
	{
		get
		{
			return this._gameType;
		}
		set
		{
			if ((this._gameType != value))
			{
				this.OngameTypeChanging(value);
				this.SendPropertyChanging();
				this._gameType = value;
				this.SendPropertyChanged("gameType");
				this.OngameTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationId", DbType="Int NOT NULL")]
	public int LocationId
	{
		get
		{
			return this._LocationId;
		}
		set
		{
			if ((this._LocationId != value))
			{
				this.OnLocationIdChanging(value);
				this.SendPropertyChanging();
				this._LocationId = value;
				this.SendPropertyChanged("LocationId");
				this.OnLocationIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNameA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string gameNameA
	{
		get
		{
			return this._gameNameA;
		}
		set
		{
			if ((this._gameNameA != value))
			{
				this.OngameNameAChanging(value);
				this.SendPropertyChanging();
				this._gameNameA = value;
				this.SendPropertyChanged("gameNameA");
				this.OngameNameAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNameB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string gameNameB
	{
		get
		{
			return this._gameNameB;
		}
		set
		{
			if ((this._gameNameB != value))
			{
				this.OngameNameBChanging(value);
				this.SendPropertyChanging();
				this._gameNameB = value;
				this.SendPropertyChanged("gameNameB");
				this.OngameNameBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameTime", DbType="DateTime NOT NULL")]
	public System.DateTime gameTime
	{
		get
		{
			return this._gameTime;
		}
		set
		{
			if ((this._gameTime != value))
			{
				this.OngameTimeChanging(value);
				this.SendPropertyChanging();
				this._gameTime = value;
				this.SendPropertyChanged("gameTime");
				this.OngameTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamestatus", DbType="Decimal(1,0) NOT NULL")]
	public decimal gamestatus
	{
		get
		{
			return this._gamestatus;
		}
		set
		{
			if ((this._gamestatus != value))
			{
				this.OngamestatusChanging(value);
				this.SendPropertyChanging();
				this._gamestatus = value;
				this.SendPropertyChanged("gamestatus");
				this.OngamestatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameLength", DbType="Int NOT NULL")]
	public int gameLength
	{
		get
		{
			return this._gameLength;
		}
		set
		{
			if ((this._gameLength != value))
			{
				this.OngameLengthChanging(value);
				this.SendPropertyChanging();
				this._gameLength = value;
				this.SendPropertyChanged("gameLength");
				this.OngameLengthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameResult", DbType="Decimal(1,0) NOT NULL")]
	public decimal gameResult
	{
		get
		{
			return this._gameResult;
		}
		set
		{
			if ((this._gameResult != value))
			{
				this.OngameResultChanging(value);
				this.SendPropertyChanging();
				this._gameResult = value;
				this.SendPropertyChanged("gameResult");
				this.OngameResultChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gameNews")]
public partial class gameNews : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gameNewsId;
	
	private decimal _userId;
	
	private int _LocationId;
	
	private string _gameNewsTitle;
	
	private string _gameNewsKeyWords;
	
	private string _gameNewsContent;
	
	private string _gameNewsAuthor;
	
	private int _gameNewsHitTimes;
	
	private System.DateTime _gameNewsCreatedTime;
	
	private int _gameNewsEditTimes;
	
	private decimal _gameNewsPriority;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngameNewsIdChanging(int value);
    partial void OngameNewsIdChanged();
    partial void OnuserIdChanging(decimal value);
    partial void OnuserIdChanged();
    partial void OnLocationIdChanging(int value);
    partial void OnLocationIdChanged();
    partial void OngameNewsTitleChanging(string value);
    partial void OngameNewsTitleChanged();
    partial void OngameNewsKeyWordsChanging(string value);
    partial void OngameNewsKeyWordsChanged();
    partial void OngameNewsContentChanging(string value);
    partial void OngameNewsContentChanged();
    partial void OngameNewsAuthorChanging(string value);
    partial void OngameNewsAuthorChanged();
    partial void OngameNewsHitTimesChanging(int value);
    partial void OngameNewsHitTimesChanged();
    partial void OngameNewsCreatedTimeChanging(System.DateTime value);
    partial void OngameNewsCreatedTimeChanged();
    partial void OngameNewsEditTimesChanging(int value);
    partial void OngameNewsEditTimesChanged();
    partial void OngameNewsPriorityChanging(decimal value);
    partial void OngameNewsPriorityChanged();
    #endregion
	
	public gameNews()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int gameNewsId
	{
		get
		{
			return this._gameNewsId;
		}
		set
		{
			if ((this._gameNewsId != value))
			{
				this.OngameNewsIdChanging(value);
				this.SendPropertyChanging();
				this._gameNewsId = value;
				this.SendPropertyChanged("gameNewsId");
				this.OngameNewsIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Decimal(8,0) NOT NULL")]
	public decimal userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationId", DbType="Int NOT NULL")]
	public int LocationId
	{
		get
		{
			return this._LocationId;
		}
		set
		{
			if ((this._LocationId != value))
			{
				this.OnLocationIdChanging(value);
				this.SendPropertyChanging();
				this._LocationId = value;
				this.SendPropertyChanged("LocationId");
				this.OnLocationIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsTitle", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string gameNewsTitle
	{
		get
		{
			return this._gameNewsTitle;
		}
		set
		{
			if ((this._gameNewsTitle != value))
			{
				this.OngameNewsTitleChanging(value);
				this.SendPropertyChanging();
				this._gameNewsTitle = value;
				this.SendPropertyChanged("gameNewsTitle");
				this.OngameNewsTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsKeyWords", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string gameNewsKeyWords
	{
		get
		{
			return this._gameNewsKeyWords;
		}
		set
		{
			if ((this._gameNewsKeyWords != value))
			{
				this.OngameNewsKeyWordsChanging(value);
				this.SendPropertyChanging();
				this._gameNewsKeyWords = value;
				this.SendPropertyChanged("gameNewsKeyWords");
				this.OngameNewsKeyWordsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsContent", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string gameNewsContent
	{
		get
		{
			return this._gameNewsContent;
		}
		set
		{
			if ((this._gameNewsContent != value))
			{
				this.OngameNewsContentChanging(value);
				this.SendPropertyChanging();
				this._gameNewsContent = value;
				this.SendPropertyChanged("gameNewsContent");
				this.OngameNewsContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsAuthor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string gameNewsAuthor
	{
		get
		{
			return this._gameNewsAuthor;
		}
		set
		{
			if ((this._gameNewsAuthor != value))
			{
				this.OngameNewsAuthorChanging(value);
				this.SendPropertyChanging();
				this._gameNewsAuthor = value;
				this.SendPropertyChanged("gameNewsAuthor");
				this.OngameNewsAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsHitTimes", DbType="Int NOT NULL")]
	public int gameNewsHitTimes
	{
		get
		{
			return this._gameNewsHitTimes;
		}
		set
		{
			if ((this._gameNewsHitTimes != value))
			{
				this.OngameNewsHitTimesChanging(value);
				this.SendPropertyChanging();
				this._gameNewsHitTimes = value;
				this.SendPropertyChanged("gameNewsHitTimes");
				this.OngameNewsHitTimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsCreatedTime", DbType="DateTime NOT NULL")]
	public System.DateTime gameNewsCreatedTime
	{
		get
		{
			return this._gameNewsCreatedTime;
		}
		set
		{
			if ((this._gameNewsCreatedTime != value))
			{
				this.OngameNewsCreatedTimeChanging(value);
				this.SendPropertyChanging();
				this._gameNewsCreatedTime = value;
				this.SendPropertyChanged("gameNewsCreatedTime");
				this.OngameNewsCreatedTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsEditTimes", DbType="Int NOT NULL")]
	public int gameNewsEditTimes
	{
		get
		{
			return this._gameNewsEditTimes;
		}
		set
		{
			if ((this._gameNewsEditTimes != value))
			{
				this.OngameNewsEditTimesChanging(value);
				this.SendPropertyChanging();
				this._gameNewsEditTimes = value;
				this.SendPropertyChanged("gameNewsEditTimes");
				this.OngameNewsEditTimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsPriority", DbType="Decimal(1,0) NOT NULL")]
	public decimal gameNewsPriority
	{
		get
		{
			return this._gameNewsPriority;
		}
		set
		{
			if ((this._gameNewsPriority != value))
			{
				this.OngameNewsPriorityChanging(value);
				this.SendPropertyChanging();
				this._gameNewsPriority = value;
				this.SendPropertyChanged("gameNewsPriority");
				this.OngameNewsPriorityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
