#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportMapDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertfriend(friend instance);
  partial void Updatefriend(friend instance);
  partial void Deletefriend(friend instance);
  partial void Insertuser(user instance);
  partial void Updateuser(user instance);
  partial void Deleteuser(user instance);
  partial void InsertgameNews(gameNews instance);
  partial void UpdategameNews(gameNews instance);
  partial void DeletegameNews(gameNews instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SportMapDBConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<friend> friend
	{
		get
		{
			return this.GetTable<friend>();
		}
	}
	
	public System.Data.Linq.Table<user> user
	{
		get
		{
			return this.GetTable<user>();
		}
	}
	
	public System.Data.Linq.Table<gameNews> gameNews
	{
		get
		{
			return this.GetTable<gameNews>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.friend")]
public partial class friend : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _userA;
	
	private string _userB;
	
	private EntityRef<user> _user;
	
	private EntityRef<user> _user1;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserAChanging(string value);
    partial void OnuserAChanged();
    partial void OnuserBChanging(string value);
    partial void OnuserBChanged();
    #endregion
	
	public friend()
	{
		this._user = default(EntityRef<user>);
		this._user1 = default(EntityRef<user>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userA", DbType="VarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string userA
	{
		get
		{
			return this._userA;
		}
		set
		{
			if ((this._userA != value))
			{
				if (this._user.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuserAChanging(value);
				this.SendPropertyChanging();
				this._userA = value;
				this.SendPropertyChanged("userA");
				this.OnuserAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userB", DbType="VarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string userB
	{
		get
		{
			return this._userB;
		}
		set
		{
			if ((this._userB != value))
			{
				if (this._user1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuserBChanging(value);
				this.SendPropertyChanging();
				this._userB = value;
				this.SendPropertyChanged("userB");
				this.OnuserBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_friend", Storage="_user", ThisKey="userA", OtherKey="userId", IsForeignKey=true)]
	public user user
	{
		get
		{
			return this._user.Entity;
		}
		set
		{
			user previousValue = this._user.Entity;
			if (((previousValue != value) 
						|| (this._user.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._user.Entity = null;
					previousValue.friend.Remove(this);
				}
				this._user.Entity = value;
				if ((value != null))
				{
					value.friend.Add(this);
					this._userA = value.userId;
				}
				else
				{
					this._userA = default(string);
				}
				this.SendPropertyChanged("user");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_friend1", Storage="_user1", ThisKey="userB", OtherKey="userId", IsForeignKey=true)]
	public user user1
	{
		get
		{
			return this._user1.Entity;
		}
		set
		{
			user previousValue = this._user1.Entity;
			if (((previousValue != value) 
						|| (this._user1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._user1.Entity = null;
					previousValue.friend1.Remove(this);
				}
				this._user1.Entity = value;
				if ((value != null))
				{
					value.friend1.Add(this);
					this._userB = value.userId;
				}
				else
				{
					this._userB = default(string);
				}
				this.SendPropertyChanged("user1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _userId;
	
	private string _imgPath;
	
	private string _userName;
	
	private string _userPwd;
	
	private decimal _userType;
	
	private string _pwdProtectA;
	
	private string _pwdProtectQ;
	
	private System.Nullable<bool> _userSex;
	
	private System.Nullable<System.DateTime> _userBirthday;
	
	private string _userConnectMsn;
	
	private System.Nullable<decimal> _userConnectqq;
	
	private string _userPrefer;
	
	private int _userLoginTimes;
	
	private System.Nullable<decimal> _userConnectPhone;
	
	private string _userSign;
	
	private string _userConnectEmail;
	
	private System.DateTime _lastLoginOutTime;
	
	private double _userLatitude;
	
	private double _userLongitude;
	
	private EntitySet<friend> _friend;
	
	private EntitySet<friend> _friend1;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(string value);
    partial void OnuserIdChanged();
    partial void OnimgPathChanging(string value);
    partial void OnimgPathChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnuserPwdChanging(string value);
    partial void OnuserPwdChanged();
    partial void OnuserTypeChanging(decimal value);
    partial void OnuserTypeChanged();
    partial void OnpwdProtectAChanging(string value);
    partial void OnpwdProtectAChanged();
    partial void OnpwdProtectQChanging(string value);
    partial void OnpwdProtectQChanged();
    partial void OnuserSexChanging(System.Nullable<bool> value);
    partial void OnuserSexChanged();
    partial void OnuserBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnuserBirthdayChanged();
    partial void OnuserConnectMsnChanging(string value);
    partial void OnuserConnectMsnChanged();
    partial void OnuserConnectqqChanging(System.Nullable<decimal> value);
    partial void OnuserConnectqqChanged();
    partial void OnuserPreferChanging(string value);
    partial void OnuserPreferChanged();
    partial void OnuserLoginTimesChanging(int value);
    partial void OnuserLoginTimesChanged();
    partial void OnuserConnectPhoneChanging(System.Nullable<decimal> value);
    partial void OnuserConnectPhoneChanged();
    partial void OnuserSignChanging(string value);
    partial void OnuserSignChanged();
    partial void OnuserConnectEmailChanging(string value);
    partial void OnuserConnectEmailChanged();
    partial void OnlastLoginOutTimeChanging(System.DateTime value);
    partial void OnlastLoginOutTimeChanged();
    partial void OnuserLatitudeChanging(double value);
    partial void OnuserLatitudeChanged();
    partial void OnuserLongitudeChanging(double value);
    partial void OnuserLongitudeChanged();
    #endregion
	
	public user()
	{
		this._friend = new EntitySet<friend>(new Action<friend>(this.attach_friend), new Action<friend>(this.detach_friend));
		this._friend1 = new EntitySet<friend>(new Action<friend>(this.attach_friend1), new Action<friend>(this.detach_friend1));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="VarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgPath", DbType="VarChar(MAX)")]
	public string imgPath
	{
		get
		{
			return this._imgPath;
		}
		set
		{
			if ((this._imgPath != value))
			{
				this.OnimgPathChanging(value);
				this.SendPropertyChanging();
				this._imgPath = value;
				this.SendPropertyChanged("imgPath");
				this.OnimgPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(16)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPwd", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
	public string userPwd
	{
		get
		{
			return this._userPwd;
		}
		set
		{
			if ((this._userPwd != value))
			{
				this.OnuserPwdChanging(value);
				this.SendPropertyChanging();
				this._userPwd = value;
				this.SendPropertyChanged("userPwd");
				this.OnuserPwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userType", DbType="Decimal(1,0) NOT NULL")]
	public decimal userType
	{
		get
		{
			return this._userType;
		}
		set
		{
			if ((this._userType != value))
			{
				this.OnuserTypeChanging(value);
				this.SendPropertyChanging();
				this._userType = value;
				this.SendPropertyChanged("userType");
				this.OnuserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwdProtectA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string pwdProtectA
	{
		get
		{
			return this._pwdProtectA;
		}
		set
		{
			if ((this._pwdProtectA != value))
			{
				this.OnpwdProtectAChanging(value);
				this.SendPropertyChanging();
				this._pwdProtectA = value;
				this.SendPropertyChanged("pwdProtectA");
				this.OnpwdProtectAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwdProtectQ", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string pwdProtectQ
	{
		get
		{
			return this._pwdProtectQ;
		}
		set
		{
			if ((this._pwdProtectQ != value))
			{
				this.OnpwdProtectQChanging(value);
				this.SendPropertyChanging();
				this._pwdProtectQ = value;
				this.SendPropertyChanged("pwdProtectQ");
				this.OnpwdProtectQChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSex", DbType="Bit")]
	public System.Nullable<bool> userSex
	{
		get
		{
			return this._userSex;
		}
		set
		{
			if ((this._userSex != value))
			{
				this.OnuserSexChanging(value);
				this.SendPropertyChanging();
				this._userSex = value;
				this.SendPropertyChanged("userSex");
				this.OnuserSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userBirthday", DbType="DateTime2")]
	public System.Nullable<System.DateTime> userBirthday
	{
		get
		{
			return this._userBirthday;
		}
		set
		{
			if ((this._userBirthday != value))
			{
				this.OnuserBirthdayChanging(value);
				this.SendPropertyChanging();
				this._userBirthday = value;
				this.SendPropertyChanged("userBirthday");
				this.OnuserBirthdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userConnectMsn", DbType="VarChar(255)")]
	public string userConnectMsn
	{
		get
		{
			return this._userConnectMsn;
		}
		set
		{
			if ((this._userConnectMsn != value))
			{
				this.OnuserConnectMsnChanging(value);
				this.SendPropertyChanging();
				this._userConnectMsn = value;
				this.SendPropertyChanged("userConnectMsn");
				this.OnuserConnectMsnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userConnectqq", DbType="Decimal(12,0)")]
	public System.Nullable<decimal> userConnectqq
	{
		get
		{
			return this._userConnectqq;
		}
		set
		{
			if ((this._userConnectqq != value))
			{
				this.OnuserConnectqqChanging(value);
				this.SendPropertyChanging();
				this._userConnectqq = value;
				this.SendPropertyChanged("userConnectqq");
				this.OnuserConnectqqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPrefer", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string userPrefer
	{
		get
		{
			return this._userPrefer;
		}
		set
		{
			if ((this._userPrefer != value))
			{
				this.OnuserPreferChanging(value);
				this.SendPropertyChanging();
				this._userPrefer = value;
				this.SendPropertyChanged("userPrefer");
				this.OnuserPreferChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userLoginTimes", DbType="Int NOT NULL")]
	public int userLoginTimes
	{
		get
		{
			return this._userLoginTimes;
		}
		set
		{
			if ((this._userLoginTimes != value))
			{
				this.OnuserLoginTimesChanging(value);
				this.SendPropertyChanging();
				this._userLoginTimes = value;
				this.SendPropertyChanged("userLoginTimes");
				this.OnuserLoginTimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userConnectPhone", DbType="Decimal(11,0)")]
	public System.Nullable<decimal> userConnectPhone
	{
		get
		{
			return this._userConnectPhone;
		}
		set
		{
			if ((this._userConnectPhone != value))
			{
				this.OnuserConnectPhoneChanging(value);
				this.SendPropertyChanging();
				this._userConnectPhone = value;
				this.SendPropertyChanged("userConnectPhone");
				this.OnuserConnectPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSign", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string userSign
	{
		get
		{
			return this._userSign;
		}
		set
		{
			if ((this._userSign != value))
			{
				this.OnuserSignChanging(value);
				this.SendPropertyChanging();
				this._userSign = value;
				this.SendPropertyChanged("userSign");
				this.OnuserSignChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userConnectEmail", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string userConnectEmail
	{
		get
		{
			return this._userConnectEmail;
		}
		set
		{
			if ((this._userConnectEmail != value))
			{
				this.OnuserConnectEmailChanging(value);
				this.SendPropertyChanging();
				this._userConnectEmail = value;
				this.SendPropertyChanged("userConnectEmail");
				this.OnuserConnectEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLoginOutTime", DbType="DateTime2 NOT NULL")]
	public System.DateTime lastLoginOutTime
	{
		get
		{
			return this._lastLoginOutTime;
		}
		set
		{
			if ((this._lastLoginOutTime != value))
			{
				this.OnlastLoginOutTimeChanging(value);
				this.SendPropertyChanging();
				this._lastLoginOutTime = value;
				this.SendPropertyChanged("lastLoginOutTime");
				this.OnlastLoginOutTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userLatitude", DbType="Float NOT NULL")]
	public double userLatitude
	{
		get
		{
			return this._userLatitude;
		}
		set
		{
			if ((this._userLatitude != value))
			{
				this.OnuserLatitudeChanging(value);
				this.SendPropertyChanging();
				this._userLatitude = value;
				this.SendPropertyChanged("userLatitude");
				this.OnuserLatitudeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userLongitude", DbType="Float NOT NULL")]
	public double userLongitude
	{
		get
		{
			return this._userLongitude;
		}
		set
		{
			if ((this._userLongitude != value))
			{
				this.OnuserLongitudeChanging(value);
				this.SendPropertyChanging();
				this._userLongitude = value;
				this.SendPropertyChanged("userLongitude");
				this.OnuserLongitudeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_friend", Storage="_friend", ThisKey="userId", OtherKey="userA")]
	public EntitySet<friend> friend
	{
		get
		{
			return this._friend;
		}
		set
		{
			this._friend.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_friend1", Storage="_friend1", ThisKey="userId", OtherKey="userB")]
	public EntitySet<friend> friend1
	{
		get
		{
			return this._friend1;
		}
		set
		{
			this._friend1.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_friend(friend entity)
	{
		this.SendPropertyChanging();
		entity.user = this;
	}
	
	private void detach_friend(friend entity)
	{
		this.SendPropertyChanging();
		entity.user = null;
	}
	
	private void attach_friend1(friend entity)
	{
		this.SendPropertyChanging();
		entity.user1 = this;
	}
	
	private void detach_friend1(friend entity)
	{
		this.SendPropertyChanging();
		entity.user1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gameNews")]
public partial class gameNews : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gameNewsId;
	
	private string _gameNewsTitle;
	
	private string _gameNewsKeyWords;
	
	private string _gameNewsContent;
	
	private string _gameNewsAuthor;
	
	private int _gameNewsHitTimes;
	
	private System.DateTime _gameNewsCreatedTime;
	
	private int _gameNewsEditTimes;
	
	private System.Nullable<decimal> _gameNewsPriority;
	
	private double _longitude;
	
	private double _latitude;
	
	private string _url;
	
	private string _gameType;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngameNewsIdChanging(int value);
    partial void OngameNewsIdChanged();
    partial void OngameNewsTitleChanging(string value);
    partial void OngameNewsTitleChanged();
    partial void OngameNewsKeyWordsChanging(string value);
    partial void OngameNewsKeyWordsChanged();
    partial void OngameNewsContentChanging(string value);
    partial void OngameNewsContentChanged();
    partial void OngameNewsAuthorChanging(string value);
    partial void OngameNewsAuthorChanged();
    partial void OngameNewsHitTimesChanging(int value);
    partial void OngameNewsHitTimesChanged();
    partial void OngameNewsCreatedTimeChanging(System.DateTime value);
    partial void OngameNewsCreatedTimeChanged();
    partial void OngameNewsEditTimesChanging(int value);
    partial void OngameNewsEditTimesChanged();
    partial void OngameNewsPriorityChanging(System.Nullable<decimal> value);
    partial void OngameNewsPriorityChanged();
    partial void OnlongitudeChanging(double value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(double value);
    partial void OnlatitudeChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OngameTypeChanging(string value);
    partial void OngameTypeChanged();
    #endregion
	
	public gameNews()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int gameNewsId
	{
		get
		{
			return this._gameNewsId;
		}
		set
		{
			if ((this._gameNewsId != value))
			{
				this.OngameNewsIdChanging(value);
				this.SendPropertyChanging();
				this._gameNewsId = value;
				this.SendPropertyChanged("gameNewsId");
				this.OngameNewsIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsTitle", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string gameNewsTitle
	{
		get
		{
			return this._gameNewsTitle;
		}
		set
		{
			if ((this._gameNewsTitle != value))
			{
				this.OngameNewsTitleChanging(value);
				this.SendPropertyChanging();
				this._gameNewsTitle = value;
				this.SendPropertyChanged("gameNewsTitle");
				this.OngameNewsTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsKeyWords", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string gameNewsKeyWords
	{
		get
		{
			return this._gameNewsKeyWords;
		}
		set
		{
			if ((this._gameNewsKeyWords != value))
			{
				this.OngameNewsKeyWordsChanging(value);
				this.SendPropertyChanging();
				this._gameNewsKeyWords = value;
				this.SendPropertyChanged("gameNewsKeyWords");
				this.OngameNewsKeyWordsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsContent", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string gameNewsContent
	{
		get
		{
			return this._gameNewsContent;
		}
		set
		{
			if ((this._gameNewsContent != value))
			{
				this.OngameNewsContentChanging(value);
				this.SendPropertyChanging();
				this._gameNewsContent = value;
				this.SendPropertyChanged("gameNewsContent");
				this.OngameNewsContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsAuthor", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
	public string gameNewsAuthor
	{
		get
		{
			return this._gameNewsAuthor;
		}
		set
		{
			if ((this._gameNewsAuthor != value))
			{
				this.OngameNewsAuthorChanging(value);
				this.SendPropertyChanging();
				this._gameNewsAuthor = value;
				this.SendPropertyChanged("gameNewsAuthor");
				this.OngameNewsAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsHitTimes", DbType="Int NOT NULL")]
	public int gameNewsHitTimes
	{
		get
		{
			return this._gameNewsHitTimes;
		}
		set
		{
			if ((this._gameNewsHitTimes != value))
			{
				this.OngameNewsHitTimesChanging(value);
				this.SendPropertyChanging();
				this._gameNewsHitTimes = value;
				this.SendPropertyChanged("gameNewsHitTimes");
				this.OngameNewsHitTimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsCreatedTime", DbType="DateTime NOT NULL")]
	public System.DateTime gameNewsCreatedTime
	{
		get
		{
			return this._gameNewsCreatedTime;
		}
		set
		{
			if ((this._gameNewsCreatedTime != value))
			{
				this.OngameNewsCreatedTimeChanging(value);
				this.SendPropertyChanging();
				this._gameNewsCreatedTime = value;
				this.SendPropertyChanged("gameNewsCreatedTime");
				this.OngameNewsCreatedTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsEditTimes", DbType="Int NOT NULL")]
	public int gameNewsEditTimes
	{
		get
		{
			return this._gameNewsEditTimes;
		}
		set
		{
			if ((this._gameNewsEditTimes != value))
			{
				this.OngameNewsEditTimesChanging(value);
				this.SendPropertyChanging();
				this._gameNewsEditTimes = value;
				this.SendPropertyChanged("gameNewsEditTimes");
				this.OngameNewsEditTimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNewsPriority", DbType="Decimal(1,0)")]
	public System.Nullable<decimal> gameNewsPriority
	{
		get
		{
			return this._gameNewsPriority;
		}
		set
		{
			if ((this._gameNewsPriority != value))
			{
				this.OngameNewsPriorityChanging(value);
				this.SendPropertyChanging();
				this._gameNewsPriority = value;
				this.SendPropertyChanged("gameNewsPriority");
				this.OngameNewsPriorityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Float NOT NULL")]
	public double longitude
	{
		get
		{
			return this._longitude;
		}
		set
		{
			if ((this._longitude != value))
			{
				this.OnlongitudeChanging(value);
				this.SendPropertyChanging();
				this._longitude = value;
				this.SendPropertyChanged("longitude");
				this.OnlongitudeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Float NOT NULL")]
	public double latitude
	{
		get
		{
			return this._latitude;
		}
		set
		{
			if ((this._latitude != value))
			{
				this.OnlatitudeChanging(value);
				this.SendPropertyChanging();
				this._latitude = value;
				this.SendPropertyChanged("latitude");
				this.OnlatitudeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(100)")]
	public string url
	{
		get
		{
			return this._url;
		}
		set
		{
			if ((this._url != value))
			{
				this.OnurlChanging(value);
				this.SendPropertyChanging();
				this._url = value;
				this.SendPropertyChanged("url");
				this.OnurlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string gameType
	{
		get
		{
			return this._gameType;
		}
		set
		{
			if ((this._gameType != value))
			{
				this.OngameTypeChanging(value);
				this.SendPropertyChanging();
				this._gameType = value;
				this.SendPropertyChanged("gameType");
				this.OngameTypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
