//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : IHtmlGenerator.cs
//  @ Date : 2010/11/20
//  @ Author : 
//
//

namespace SportMap.BLL
{
    public interface IHtmlGenerator
    {
        string getHtml();
    }
}