//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : SearchEngine.cs
//  @ Date : 2010/11/20
//  @ Author : 
//
//

namespace SportMap.BLL
{
    public class SearchEngine {
	    private SEARCHTYPE type ;
	    public messageList ArrayList<News>;
	    public void MessageSearch(System.Collections.ArrayList<News> messageList, SEARCHTYPE type){
	    }
	    public ArrayList<News> geNewest(){
	    }
	    public ArrayList<Friend> getFriendList(){
	    }
	    public void MessageSearch(){
	    }
	    public ArrayList<News> search(){
	    }
	    public ArrayList<News> getSubjectNews(){
	    }
    }
}