//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : SEARCHTYPE.cs
//  @ Date : 2010/11/20
//  @ Author : 
//
//

namespace SportMap.BLL
{
    public enum SEARCHTYPE
    {
        NORMAL,
        LOCATION,
        SPORT,
        FRIEND,
        VIDEO,
        PICTURE,
        TEXT
    }
}