//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : UserLoginInit.cs
//  @ Date : 2010/11/20
//  @ Author : 
//
//

namespace SportMap.BLL
{
    private class UserLoginInit
    {
        private User user;
        public void sendUserSportMessages()
        {
        }
        public void sendUserBetMessages()
        {
        }
        public void updateMoney()
        {
        }
        public ArrayList<Message> getFavoriteNews()
        {
        }
        public void UserLoginInit(User user)
        {
        }
    }
}